"""Static Gain Calibration Report Generator Script
5/20/2025
"""
import os
import numpy as np
from reportlab.lib.units import cm
from reportlab.pdfgen.canvas import Canvas
# from reportlab.platypus import Frame, Image


# ==========================================
# PART 1: STATISTICAL ANALYSIS
# ==========================================

report_file = "Data/RmsData.txt"
failing_units = []
stats_summary = []

if os.path.exists(report_file):
    # Read the data file generated by the collection script
    # CSV Format: RX1, RX2, RX3, RX4, RY1, RY2, RY3, RY4, BPMname
    # We want RX4 (Index 3) and RY4 (Index 7) -> "Beam with Old SG Table"

    data_lines = []
    with open(report_file, 'r') as f:
        # Read lines and split by comma
        data_lines = [line.strip().split(',') for line in f if line.strip()]

    # Parse into lists for analysis
    rx4_vals = []
    ry4_vals = []
    bpm_names = []

    for row in data_lines:
        if len(row) < 9:
            continue  # Skip malformed lines
        try:
            # RX4 is index 3, RY4 is index 7
            val_x = float(row[3])
            val_y = float(row[7])

            rx4_vals.append(val_x)
            ry4_vals.append(val_y)
            bpm_names.append(row[8])       # Name is last column
        except ValueError:
            continue

    if len(rx4_vals) > 0:
        # Convert to numpy for easy stats
        x_arr = np.array(rx4_vals)
        y_arr = np.array(ry4_vals)

        # Calculate Statistics (Mean + 3 Sigma)
        # We calculate the mean of the CURRENT data (this run)
        # to find relative outliers
        mean_x = np.mean(x_arr)
        std_x = np.std(x_arr)
        limit_x = mean_x + (3 * std_x)

        mean_y = np.mean(y_arr)
        std_y = np.std(y_arr)
        limit_y = mean_y + (3 * std_y)

        stats_summary.append(f"Analyzed {len(bpm_names)} "
                             "BPMs (Existing Tables)")
        stats_summary.append(f"X Threshold (Mean: {mean_x:.2f}"
                             f" + 3s): {limit_x:.3f}")
        stats_summary.append(f"Y Threshold (Mean: {mean_y:.2f}"
                             f" + 3s): {limit_y:.3f}")

        # Find Outliers
        for i, name in enumerate(bpm_names):
            reasons = []
            if x_arr[i] > limit_x:
                reasons.append(f"X-RMS High ({x_arr[i]:.2f})")
            if y_arr[i] > limit_y:
                reasons.append(f"Y-RMS High ({y_arr[i]:.2f})")

            if reasons:
                failing_units.append(f"{name}: " + ", ".join(reasons))
    else:
        stats_summary.append("Error: No valid data found in RmsData.txt")

else:
    stats_summary.append("Error: Data/RmsData.txt not found.")


# ==========================================
# PART 2: GENERATE SUMMARY PAGE
# ==========================================

c = Canvas('SRreport.pdf')
c.setPageSize((43*cm, 24*cm))

# --- DRAW SUMMARY PAGE ---
c.setFont("Helvetica-Bold", 24)
c.drawString(2*cm, 21*cm, "Static Gain Calibration Summary")

c.setFont("Helvetica", 14)
text_y = 19*cm

# Print Statistics
for line in stats_summary:
    c.drawString(2*cm, text_y, line)
    text_y -= 0.8*cm

text_y -= 1*cm  # Gap
c.setFont("Helvetica-Bold", 18)
c.drawString(2*cm, text_y, "Outliers (Existing Tables):")
text_y -= 1*cm

# Print Failures
if not failing_units:
    c.setFillColorRGB(0, 0.5, 0)  # Green
    c.drawString(2*cm, text_y, "No outliers detected. All units passed.")
else:
    c.setFillColorRGB(1, 0, 0)  # Red
    c.setFont("Helvetica-Bold", 14)

    # Split into two columns if list is long
    col_x = 2*cm
    count = 0
    for fail in failing_units:
        c.drawString(col_x, text_y, fail)
        text_y -= 0.8*cm
        count += 1

        # Move to next column after 15 items
        if count == 15:
            col_x = 20*cm
            text_y = 17*cm  # Reset Y for second column

c.showPage()  # End of Summary Page

# Reset color to black for the rest of the report
c.setFillColorRGB(0, 0, 0)


# Note that all spacial entries such as X, Y coordinates or item height
# and width must be multiplies by the constant 'cm' which was imported
# above and converts the centimeter units into the native units used in
# Reportlab's internal code.

c = Canvas('SRreport.pdf')
c.setPageSize((43*cm, 24*cm))

# Cell 1:
# Syntax: c.drawImage('Imagefile.png', X, Y, Width, Height)
# where:
#       'Imagefile.png' is the name of the BPM image PNG file created by
#        the data collection script.
#       'X, Y' are the coordinates of the lower left corner of the image
#       'Width, Height' are the dimensions of the image
c.drawImage('Images/SR:C01-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C01-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C01-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C01-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C01-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C01-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
# Syntax: c.drawString(X, Y, 'string')
# where:
#    'X, Y' are the coodinates on the page for the string
#   'string' is the string to be displayed at that location
c.drawString(1*cm, 23*cm, "Cell 1: ARC BPMs 1 through 6:")
# Syntax: c.line(X1, Y1, X2, Y2)
# where:
#   'X1, Y1' are the start coodinates on the page for the line
#   'X2, Y2' are the end coodinates on the page for the line
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 1: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

#  2:
c.drawImage('Images/SR:C02-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C02-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 2: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 2: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 3:
c.drawImage('Images/SR:C03-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C03-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 3: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 3: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 4:
c.drawImage('Images/SR:C04-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C04-BI{BPM:10}.png', 34*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 4: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 4: ID BPMs 7 through 10:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 5:
c.drawImage('Images/SR:C05-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C05-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 5: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 5: ID BPMs 7 through 9:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 6:
c.drawImage('Images/SR:C06-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C06-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C06-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C06-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C06-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C06-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 6: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 6: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 7:
c.drawImage('Images/SR:C07-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C07-BI{BPM:10}.png', 34*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 7: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 7: ID BPMs 7 through 10:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 8:
c.drawImage('Images/SR:C08-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C08-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 8: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 8: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 9:
c.drawImage('Images/SR:C09-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C09-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C09-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C09-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C09-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C09-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 9: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 9: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 10:
c.drawImage('Images/SR:C10-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C10-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 10: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 10: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 11:
c.drawImage('Images/SR:C11-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C11-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 11: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 11: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 12:
c.drawImage('Images/SR:C12-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C12-BI{BPM:10}.png', 34*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 12: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cel1 12: ID BPMs 7 through 10:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 13:
c.drawImage('Images/SR:C13-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C13-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C13-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C13-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C13-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C13-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 13: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 13: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 14:
c.drawImage('Images/SR:C14-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C14-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C14-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C14-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C14-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C14-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 14: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 14: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 15:
c.drawImage('Images/SR:C15-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C15-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C15-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C15-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C15-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C15-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 15: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 15: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 16:
c.drawImage('Images/SR:C16-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C16-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 16: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 16: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 17:
c.drawImage('Images/SR:C17-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C17-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 17: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 17: ID BPMs 7 through 9:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 18:
c.drawImage('Images/SR:C18-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C18-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 18: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 18: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 19:
c.drawImage('Images/SR:C19-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C19-BI{BPM:10}.png', 34*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 19: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 19: ID BPMs 7 through 10:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 20:
c.drawImage('Images/SR:C20-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C20-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 20: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 20: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 21:
c.drawImage('Images/SR:C21-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C21-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 21: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 21: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 22:
c.drawImage('Images/SR:C22-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C22-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C22-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C22-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C22-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C22-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 22: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 22: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 23:
c.drawImage('Images/SR:C23-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C23-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 23: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 23: ID BPMs 7 through 9:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 24:
c.drawImage('Images/SR:C24-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C24-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C24-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C24-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C24-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C24-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 24: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 24: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 25:
c.drawImage('Images/SR:C25-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C25-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C25-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C25-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C25-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C25-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 25: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 25: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 26:
c.drawImage('Images/SR:C26-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C26-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C26-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C26-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C26-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C26-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 26: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 26: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 27:
c.drawImage('Images/SR:C27-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C27-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 27: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 27: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 28:
c.drawImage('Images/SR:C28-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C28-BI{BPM:8}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 28: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 28: ID BPMs 7 through 8:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 29:
c.drawImage('Images/SR:C29-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C29-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C29-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C29-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C29-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C29-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 29: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 29: No ID BPMs")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()

# Cell 30:
c.drawImage('Images/SR:C30-BI{BPM:1}.png', 0*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:2}.png', 8.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:3}.png', 17*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:7}.png', 25.5*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:8}.png', 34*cm, 11.5*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:4}.png', 0*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:5}.png', 8.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:6}.png', 17*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:9}.png', 25.5*cm, 0*cm, 9*cm, 12*cm)
c.drawImage('Images/SR:C30-BI{BPM:10}.png', 34*cm, 0*cm, 9*cm, 12*cm)
c.drawString(1*cm, 23*cm, "Cell 30: ARC BPMs 1 through 6:")
c.line(0.2*cm, 0.2*cm, 0.2*cm, 23.5*cm)
c.line(0.2*cm, 0.2*cm, 25.4*cm, 0.2*cm)
c.line(0.2*cm, 23.5*cm, 25.4*cm, 23.5*cm)
c.line(25.4*cm, 0.2*cm, 25.4*cm, 23.5*cm)
c.drawString(26.5*cm, 23*cm, "Cell 30: ID BPMs 7 through 10:")
c.line(25.7*cm, 0.2*cm, 42.7*cm, 0.2*cm)
c.line(25.7*cm, 0.2*cm, 25.7*cm, 23.5*cm)
c.line(42.7*cm, 0.2*cm, 42.7*cm, 23.5*cm)
c.line(25.7*cm, 23.5*cm, 42.7*cm, 23.5*cm)
c.showPage()
c.save()
